name: Build and push
on:
  push:
    branches: [main]
jobs:
  build-and-push:
    name: ðŸ†
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y sox libsox-fmt-mp3
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          # cache: 'npm'
      - run: npm install
      - run: npm run build
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: igua-rpg
          ITCH_USER: hubol
          PACKAGE: dist
      # https://izy.codes/heroku-deploy-static-html-en/
      - run: >
          echo '<?php include_once("index.html"); ?>' > index.php &&
          echo '{}' > composer.json
        working-directory: dist
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: igua-rpg
          heroku_email: hubol.gordon@gmail.com
          appdir: dist
